### ISSUE TITLE
Division by 0 in poly_is_hole(poly)

### ISSUE THREAD

**Issue by gaellafond** [mmccoo/kicad_mmccoo#3]
[EDIT} Affected file:
kicad_mmccoo/svg2border/parse_svg_path.py

Nice library!

I'm trying to create an InkScape plugin and I'm having issue determining if a polygon is a hole. I found your code so I decided to have a go. If I call ```poly_is_hole(poly)``` on a shape that has 2 consecutive points aligned on X (like a rectangle for example), the function returns:
```
Traceback (most recent call last):
  File "parse_svg_path.py", line 397, in <module>
    print("        hole: " + poly_is_hole(poly))
  File "parse_svg_path.py", line 388, in poly_is_hole
    area = area + (pt[0]-lastpt[0])/(pt[1]+lastpt[1])
```
NOTE: I added this at the end of the file (line 397):
    ```print("        hole: " + str(poly_is_hole(poly)))```

In your code comments, you said the logic is from this post:
    https://stackoverflow.com/a/1165943/23630
I had a look and it turns out you are not applying the logic properly (looks like a typo). You are doing x/y instead of x*y

Replace line 388
    ```area = area + (pt[0]-lastpt[0])/(pt[1]+lastpt[1])```
with
    ```area = area + (pt[0]-lastpt[0])*(pt[1]+lastpt[1])```

**Comment by mmccoo** [comment]
thank you for taking the time to report this issue. I have fixed it.

I've also moved the code around a little to make it callable as a pcbnew plugin.
