### ISSUE TITLE
New orientation needed in place_by_sch

### ISSUE THREAD

**Issue by TomWS1** [mmccoo/kicad_mmccoo#6]
I ran into a python error when I ran place_by_sch on a recent design.  It turned out to be a component that had an orientation that was not in the orientations table (flipped but no rotation).  I fixed my local copy and, I'm embarrassed to say I'm not enough of a git user to confidently generate a pull request.
Here are the two lines I added:
at line 47 I added the line:
    t0f  = '	1    0    0    1'  # TWS this is also flipped horizontally with rotation
at line 54 I added the line:
        str(trans_p.match(t0f).groups()): 0,  # TWS added to handle flipped, but no rotation

I'm attaching the new file in case that's easier for you to manage.
[place_by_sch.zip](https://github.com/mmccoo/kicad_mmccoo/files/2236509/place_by_sch.zip)

**Comment by mmccoo** [comment]
thank you for the fix. I have applied and pushed it.

A for pull requests... I haven't done them either.  The closest I've gotten is kicad submissions. They don't want pull requests but rather patch files emailed to their list.

Probably before learning pull requests, I recommend becoming familiar (if you aren't already) with the patch command. You probably seen diff's output. The patch command takes that as input.
 
super handy

thanks again. Bug reports is one of the ways I know people out there actually use this stuff. Gives me a reason to bother.
